mary = "Mary <mary@mary.zone>"
roblabla = "roblabla <unfiltered@roblab.la>"
wearr = "wearrrrr <contact@wearr.dev>"
VieRo = "PieVieRo <tymek24m@gmail.com>"
reisen = "[[Reisen]] <95779166+0x32767@users.noreply.github.com>"
renzo904 = "Renzo904 <63516530+Renzo904@users.noreply.github.com>"
